#!/usr/bin/python

from dandolib import *
from time import sleep

d = Dash("dc:65:0f:de:4f:8b")
#d = Dot("ef:d0:c2:36:5a:3a")
print "Connected to "+d.name
d.setWait4IdleFlag(True)

# SOUNDS
print "BYEBYE"   ; d.sound(BYEBYE)
#print "COOL"    ; d.sound(COOL)
print "HAHA"     ; d.sound(HAHA)
print "HI"       ; d.sound(HI)
print "LETSGO"   ; d.sound(LETSGO)
print "TRUMPET"  ; d.sound(TRUMPET)
print "TAHDAH"   ; d.sound(TAHDAH)
print "UHUH"     ; d.sound(UHUH)
print "UHOH"     ; d.sound(UHOH)
print "YIPPE"    ; d.sound(YIPPE)
print "OOH"      ; d.sound(OOH)
print "OHYEAH"   ; d.sound(OHYEAH)
print "OHNO"     ; d.sound(OHNO)
print "WOW"      ; d.sound(WOW)
print "WOW2"     ; d.sound(WOW2)
print "CONFUSED" ; d.sound(CONFUSED)
print "GIGGLE"   ; d.sound(GIGGLE)
print "GOBBLE"   ; d.sound(GOBBLE)
print "GRUNT"    ; d.sound(GRUNT)
print "SIGN"     ; d.sound(SIGN)
print "SNORE"    ; d.sound(SNORE)
print "SQUEAK"   ; d.sound(SQUEAK)
print "SURPRISED"; d.sound(SURPRISED)
print "WAH"      ; d.sound(WAH)
print "WEEHEE"   ; d.sound(WEEHEE)
print "YAWN"     ; d.sound(YAWN)
print "CAT"      ; d.sound(CAT)
print "CROCODILE"; d.sound(CROCODILE)
print "DINOSAUR" ; d.sound(DINOSAUR)
print "COW"      ; d.sound(COW)
print "DOG"      ; d.sound(DOG)
print "ELEPHANT" ; d.sound(ELEPHANT)
print "GOAT"     ; d.sound(GOAT)
print "HORSE"    ; d.sound(HORSE)
print "LION"     ; d.sound(LION)
print "TRUCK"    ; d.sound(TRUCK)
print "HORN"     ; d.sound(HORN)
print "SIREN"    ; d.sound(SIREN)
print "TIRE"     ; d.sound(TIRE)
print "AIRPLANE" ; d.sound(AIRPLANE)
print "BEEP"     ; d.sound(BEEP)
print "BOAT"     ; d.sound(BOAT)
print "BUZZ"     ; d.sound(BUZZ)
print "HELICOPTER"; d.sound(HELICOPTER)
print "LASERS"   ; d.sound(LASERS)
print "SPEEDBOOST"; d.sound(SPEEDBOOST)
print "ENGINEREV"; d.sound(ENGINEREV)
print "TRAIN"    ; d.sound(TRAIN)
