#!/usr/bin/python

from dandolib import *
from time import sleep

#d = Dash("dc:65:0f:de:4f:8b")
d = Dot("ef:d0:c2:36:5a:3a")
print "Connected to "+d.name

# SOUNDS
d.sound(BYEBYE)
d.sound(COOL)
d.sound(HAHA)
d.sound(HI)
d.sound(LETSGO)
d.sound(TRUMPET)
d.sound(TAHDAH)
d.sound(UHUH)
d.sound(UHOH)
d.sound(YIPPE)
d.sound(OOH)
d.sound(OHYEAH)
d.sound(OHNO)
d.sound(WOW)
d.sound(WOW2)
d.sound(CONFUSED)
d.sound(GIGGLE)
d.sound(GOBBLE)
d.sound(GRUNT)
d.sound(SIGN)
d.sound(SNORE)
d.sound(SQUEAK)
d.sound(SURPRISED)
d.sound(WAH)
d.sound(WEEHEE)
d.sound(YAWN)
d.sound(CAT)
d.sound(CROCODILE)
d.sound(DINOSAUR)
d.sound(COW)
d.sound(DOG)
d.sound(ELEPHANT)
d.sound(GOAT)
d.sound(HORSE)
d.sound(LION)
d.sound(TRUCK)
d.sound(HORN)
d.sound(SIREN)
d.sound(TIRE)
d.sound(AIRPLANE)
d.sound(BEEP)
d.sound(BOAT)
d.sound(BUZZ)
d.sound(HELICOPTER)
d.sound(LASERS)
d.sound(SPEEDBOOST)
d.sound(ENGINEREV)
d.sound(TRAIN)
